config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "admin/cocktails#index"

  namespace :admin do
    resources :categories
    resources :cocktails
  end

  namespace :api do
    namespace :v1 do
      resources :categories, only: %i[index]
      resources :cocktails, only: %i[index show]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :cocktails
end

app/models/cocktail.rb
# frozen_string_literal: true

class Cocktail < ApplicationRecord
  include ImageUploader::Attachment(:image)

  validates :name, presence: true, uniqueness: true
  validates :signature, inclusion: { in: [true, false] }
  validates :menu, inclusion: { in: [true, false] }

  belongs_to :category
  delegate :name, to: :category, prefix: true

  def video_id
    _, id = youtube_link.split("=")
    id.nil? ? "" : id
  end
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

module Admin
  class CategoriesController < ApplicationController
    expose(:categories) { Category.all }
    expose(:category)

    def index; end

    def show; end

    def new; end

    def edit; end

    def create
      if category.save
        redirect_to admin_category_url(category), notice: 'Category was successfully created.'
      else
        render :new
      end
    end

    def update
      if category.update(category_params)
        redirect_to admin_category_url(category), notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      category.destroy
      redirect_to admin_categories_url, notice: 'Category was successfully destroyed.'
    end

    private

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/admin/cocktails_controller.rb
# frozen_string_literal: true

module Admin
  class CocktailsController < ApplicationController
    expose(:cocktails) { Cocktail.all.order(updated_at: :desc) }
    expose(:cocktail)

    def index; end

    def show; end

    def new; end

    def edit; end

    def create
      if cocktail.valid?
        cocktail.image_derivatives! if cocktail.image_changed?
        cocktail.save
        redirect_to admin_cocktail_path(cocktail), notice: 'Cocktail was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /cocktails/1
    def update
      cocktail.assign_attributes(cocktail_params)
      if cocktail.valid?
        cocktail.image_derivatives! if cocktail.image_changed?
        cocktail.save
        redirect_to admin_cocktail_path(cocktail), notice: 'Cocktail was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      cocktail.destroy
      redirect_to admin_cocktails_url, notice: 'Cocktail was successfully destroyed.'
    end

    private

    def cocktail_params
      params.require(:cocktail).permit(
        :name,
        :ingredients,
        :glassware,
        :technique,
        :garnish,
        :signature,
        :menu,
        :category_id,
        :youtube_link,
        :image
      )
    end
  end
end

app/controllers/api/v1/api_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ApiController < ActionController::API
      before_action :set_format_to_json

      private

      def set_format_to_json
        request.format = :json
      end
    end
  end
end

app/controllers/api/v1/categories_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CategoriesController < ApiController
      expose(:categories) { Category.all }
      expose(:category)

      def index; end
    end
  end
end

app/controllers/api/v1/cocktails_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CocktailsController < ApiController
      expose(:cocktails) { Cocktail.includes(:category).all }
      expose(:cocktail, find_by: :uuid)

      def index; end

      def show; end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/admin/categories_helper.rb
# frozen_string_literal: true

module Admin
  module CategoriesHelper
  end
end

app/helpers/api/v1/categories_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module CategoriesHelper
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cocktails_helper.rb
# frozen_string_literal: true

module CocktailsHelper
  def signature_badge_class(cocktail)
    cocktail.signature ? "badge badge-primary" : "badge badge-secondary"
  end

  def signature_label(cocktail)
    cocktail.signature ? t(".signature") : t(".not_signature")
  end
end

app/views/admin/categories/_form.html.haml
= form_with model: [:admin, category] do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(category.errors.count, "error")} prohibited this admin_category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/admin/categories/edit.html.haml
%h1 Editing admin_category

= render 'form'

= link_to 'Show', admin_category_path(category)
\|
= link_to 'Back', admin_categories_path

app/views/admin/categories/index.html.haml
%h1 Listing admin_categories

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - categories.each do |category|
      %tr
        %td= category.name
        %td= link_to 'Show', admin_category_path(category)
        %td= link_to 'Edit', edit_admin_category_path(category)
        %td= link_to 'Destroy', admin_category_path(category), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_admin_category_path

app/views/admin/categories/new.html.haml
%h1 New admin_category

= render 'form'

= link_to 'Back', admin_categories_path

app/views/admin/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = category.name

= link_to 'Edit', edit_admin_category_path(category)
\|
= link_to 'Back', admin_categories_path

app/views/admin/cocktails/_form.html.haml
= form_with model: [:admin, cocktail] do |f|
  - if cocktail.errors.any?
    #error_explanation
      %h2= "#{pluralize(cocktail.errors.count, "error")} prohibited this cocktail from being saved:"
      %ul
        - cocktail.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category
    = f.collection_select(:category_id, Category.all, :id, :name)
  .field
    = f.label :ingredients
    = f.text_area :ingredients
  .field
    = f.label :glassware
    = f.text_field :glassware
  .field
    = f.label :technique
    = f.text_area :technique
  .field
    = f.label :garnish
    = f.text_field :garnish
  .field
    = f.hidden_field :image, value: cocktail.cached_image_data
    = f.label :image
    = f.file_field :image
  .field
    = f.label :youtube_link
    = f.text_field :youtube_link
  .field
    = f.label :signature
    = f.check_box :signature
  .field
    = f.label :menu
    = f.check_box :menu
  .actions
    = f.submit 'Save'

app/views/admin/cocktails/edit.html.haml
%h1 Editing cocktail

= render 'form'

= link_to 'Show', admin_cocktail_path(cocktail)
\|
= link_to 'Back', admin_cocktails_path

app/views/admin/cocktails/index.html.haml
%h1 Listing cocktails

%p#notice= notice

= link_to 'New Cocktail', new_admin_cocktail_path, class: "btn btn btn-success mt-2 mb-4"

.cocktails.container.mx-auto.d-flex.flex-column.flex-lg-row.flex-wrap.justify-around
  - cocktails.each do |cocktail|
    .card.mr-2.mb-2.w-lg-25
      = link_to admin_cocktail_path(cocktail) do
        = image_tag(asset_path(cocktail.image_url(:small)), class: "card-img-top")
      .card-body
        .d-inline-flex.mb-4
          %span{class: signature_badge_class(cocktail)}= signature_label(cocktail)
        %h5.card-title= cocktail.name
        %h6.card-title= t(".ingredients")
        %p.card-text= cocktail.ingredients
        %h6.card-title= t(".glassware")
        %p.card-text= cocktail.glassware
        %h6.card-title= t(".technique")
        %p.card-text= cocktail.technique
        %h6.card-title= t(".garnish")
        %p.card-text= cocktail.garnish

        =link_to 'Show', admin_cocktail_path(cocktail), class: "btn btn-primary"
        =link_to 'Edit', edit_admin_cocktail_path(cocktail), class: "btn btn-primary"
        =link_to 'Destroy', admin_cocktail_path(cocktail), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"

app/views/admin/cocktails/new.html.haml
%h1 New cocktail

= render 'form'

= link_to 'Back', admin_cocktails_path

app/views/admin/cocktails/show.html.haml
%p#notice= notice

.cocktail.container.mx-auto.d-flex.justify-content-center
  .card
    %img.card-img-top{src: cocktail.image_url(:small)}
    .card-body
      .d-inline-flex.mb-4
        %span{class: signature_badge_class(cocktail)}= signature_label(cocktail)
      %h5.card-title= cocktail.name
      %h6.card-title= t(".youtube_link")
      %p.card-text= cocktail.youtube_link
      %h6.card-title= t(".ingredients")
      %p.card-text= cocktail.ingredients
      %h6.card-title= t(".glassware")
      %p.card-text= cocktail.glassware
      %h6.card-title= t(".technique")
      %p.card-text= cocktail.technique
      %h6.card-title= t(".garnish")
      %p.card-text= cocktail.garnish

      = link_to 'Edit', edit_admin_cocktail_path(cocktail), class: "btn btn-primary"
      = link_to 'Back', admin_cocktails_path, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BarBook
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload'
    -#= stylesheet_packs_with_chunks_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield